### ISSUE TITLE
Rumour eval todo list

### ISSUE THREAD

**Issue by t0ngliu** [josephroqueca/rumoureval#1]
- [x] Baseline
  - [x] Using bag of words and vectorized the bag
- [ ] Integrate NLTK
- [ ] Report
  - [ ] Abstract, introduction, motivation
  - [ ] Data
    - [ ] Training
    - [ ] Validation
    - [ ] Testing
    - [ ] Annotation
  - [ ] Text categorization model
    - [ ] Bag of words
    - [ ] N-Gram
  - [ ] Preparing data
    - [ ] Filtering, including stop words
    - [ ] Feature extraction
    - [ ] Use of NLTK
  - [ ] Training classifier, building a pipline
    - [ ] Algorithms
      - [ ] Naive Bayes
      - [ ] SVM
    - [ ] Baseline
    - [ ] Evaluation
    - [ ] Parameter tuning
  - [ ] Discussion
  - [ ] Conclusion
  - [ ] Future work
- [ ] Presentation
